### ISSUE TITLE
Problems with cbindgen 0.4

### ISSUE THREAD

**Issue by frip** [getsentry/milksnake#13]
I could not build the example with dependency `cbindgen = "0.4"`: got 
```
error[E0425]: cannot find function `parse_crate` in module `syn`
```
 etc.

Changing to `cbindgen = "0.5"` fixed it.

**Comment by mitsuhiko** [comment]
Yeah. I noticed. But i think cbindgen 0.5 currently needs nightly unless that was already fixed.

**Comment by frip** [comment]
Seems to work now (with `rustc 1.25.0`)

**Comment by saethlin** [comment]
With `cbindgen = "0.5.2"` I can build the example on stable.  At first, cargo selected 0.5.0 for me, which appears to require nightly.
Can anyone else confirm?

**Comment by onelson** [comment]
I was able to build with 0.5.2 on 1.25 without issue.

**Comment by nim65s** [comment]
Same issue here with 0.4. 
Using 0.8 allowed me to build the example.
